"""
Django settings for djangfolio project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from djangfolio.settings.base import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "_c*4j)y%xg+77wyba+mim-m839tcm=tpu&)jo9axh#a$vmh9y7"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

RECAPTCHA_PUBLIC_KEY = ""
RECAPTCHA_PRIVATE_KEY = ""
