---

name: Build Production Docker Image
on:
  push:
    branches: [ master ]

jobs:
    build-docker:
        name: "Build Production Docker Image"
        runs-on: "ubuntu-latest"
        env:
            DOCKER_LATEST: docker.pkg.github.com/kioui/djangfolio/djangfolio:latest
            DOCKER_TAG_PRODUCTION: docker.pkg.github.com/kioui/djangfolio/djangfolio:${{ github.sha }}
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v2"
              
            - name: "Set up Docker Buildx"
              uses: "crazy-max/ghaction-docker-buildx@v3"
              with:
                buildx-version: latest
                qemu-version: latest

            - name: "Build Docker image"
              run: |
                  docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t "${DOCKER_LATEST}" .
                  docker buildx build --load -t "${DOCKER_LATEST}" .

            - name: "Login to GitHub"
              run: echo "${{ secrets.GH_TOKEN }}" | docker login docker.pkg.github.com -u KiOui --password-stdin
            
            - name: "Tag and publish"
              run: |
                  docker tag "${DOCKER_LATEST}" "${DOCKER_TAG_PRODUCTION}"
                  docker push "${DOCKER_TAG_PRODUCTION}"
                  docker push "${DOCKER_LATEST}"
