# Generated by Django 3.0.5 on 2020-04-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="Show on homepage"),
                ),
                ("picture", models.ImageField(upload_to="profile_images/")),
                ("first_name", models.CharField(blank=True, max_length=512)),
                ("second_name", models.CharField(blank=True, max_length=512)),
                (
                    "short_function_description",
                    models.CharField(blank=True, max_length=4096),
                ),
                ("about_me", models.TextField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                (
                    "about_me_title",
                    models.CharField(default="About me", max_length=512),
                ),
                ("career_title", models.CharField(default="Career", max_length=512)),
                (
                    "projects_title",
                    models.CharField(default="Projects", max_length=512),
                ),
                (
                    "contact_me_title",
                    models.CharField(default="Contact me", max_length=512),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateField(null=True)),
                ("end_time", models.DateField(null=True)),
                ("title", models.CharField(max_length=512)),
                ("image", models.ImageField(upload_to="")),
                ("description", models.TextField(blank=True, null=True)),
                ("short_description", models.CharField(blank=True, max_length=4096)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.Profile",
                    ),
                ),
            ],
            options={"ordering": ["-start_time"],},
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateField()),
                ("end_time", models.DateField(null=True)),
                ("title", models.CharField(max_length=512)),
                ("short_description", models.TextField(blank=True)),
                ("institution", models.CharField(blank=True, max_length=256)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.Profile",
                    ),
                ),
            ],
            options={"ordering": ["-start_time"],},
        ),
    ]
